version: '3'

dotenv:
  - .env

vars:
  DB_URL: postgres://{{.POSTGRES_USER}}:{{.POSTGRES_PASSWORD}}@{{.POSTGRES_HOST}}:{{.POSTGRES_PORT}}/{{.POSTGRES_DB}}?sslmode=disable

tasks:
  upmigrations:
    cmds:
      - migrate -path ./migrations -database "{{.DB_URL}}" up